### ISSUE TITLE
not working dynamically 

### ISSUE THREAD

**Issue by dinesh0666** [tylerecouture/summernote-math#2]
Please fix

**Comment by tylerecouture** [comment]
Can you be more specific?  The example pages is working for me: https://rawgit.com/tylerecouture/summernote-math/master/Example/example.html

**Comment by tylerecouture** [comment]
The only thing I can find is that if you paste in the latex you need to hit spacebar or something else to trigger the math to appear in the popup.  Let me know if there is something else. Thanks!
